name: braket-demo
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  braket:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.GH_BRAKET_ROLE_ARN }}
          aws-region: us-east-1

      - name: Debug env
        run: |
          set -x
          aws --version
          aws sts get-caller-identity
          aws configure list

      - name: Braket smoke (non-fatal, multi-region)
        run: |
          set -e
          ok=false
          for r in us-east-1 us-west-2 us-west-1; do
            echo ">>> Trying region: $r"
            if aws braket search-devices --max-results 1 --region "$r"; then
              ok=true; break
            fi
          done
          if [ "$ok" = false ]; then
            echo "Braket query failed in tried regions; continuing."
          fi
        shell: bash
        continue-on-error: true
