name: braket-demo
on: { workflow_dispatch: {} }
permissions: { id-token: write, contents: read }
jobs:
  braket:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.GH_BRAKET_ROLE_ARN }}
          aws-region: us-east-1
      - name: Verify identity
        run: aws sts get-caller-identity
      - name: Braket device probe (SV1)
        run: aws braket get-device --device-arn arn:aws:braket:::device/quantum-simulator/amazon/sv1 --region us-east-1
